name: 'Test Coverage'

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  coverage:
    uses: decaf-ts/reusable-actions/.github/workflows/jest-coverage.yaml@main
    secrets: inherit
