name: "Pages Builder"

on:
  workflow_dispatch: # on button click
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches: [ master, main ]
    paths:
      - workdocs/**
      - .github/workflows/pages.yaml

jobs:
  deploy:
    uses: decaf-ts/reusable-actions/.github/workflows/pages.yaml@main
    secrets: inherit
