name: "Run on PR Merge to Master"

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
        language: ["javascript"]
    steps:
      - name: Checkout
        # actions/checkout@v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        # actions/setup-node@v4
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci --ignore-scripts
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump TAG
        run: npm version patch

      - name: Build
        run: npm run build:prod

      - name: Test
        run: npm run coverage

      - name: Commit changes
        run: |
          TAG=$(git describe --tags --exact-match || echo "no-tag")
          git add .
          git commit -m  "Github Action automatic release: ${TAG_NAME}" || echo "No changes to commit"
          git push origin HEAD:master --follow-tags