name: "Release on Tag"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '!*-no-ci'
  workflow_dispatch:

jobs:
  deploy:
    uses: decaf-ts/reusable-actions/.github/workflows/release-on-tag.yaml@main
    secrets: inherit
