name: Renovate

on:
  repository_dispatch:
    types: [renovate-trigger]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # actions/checkout@v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Renovate
        # renovatebot/github-action@v46.1.15
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd
        with:
          configurationFile: renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
