name: "Snyk Analysis"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!*-alpha'
      - '!*-no-ci'
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    uses: decaf-ts/reusable-actions/.github/workflows/snyk-analysis.yaml@main
    secrets: inherit
