name: "Snyk Analysis"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!*-alpha'
      - '!*-no-ci'
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      # actions/checkout@v4
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Run Snyk to check for vulnerabilities
        # snyk/actions/node@master (pinned to commit)
        uses: snyk/actions/node@8e119fbb6c251787721d34ba683ed48eba792766
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        if: always()
        # github/codeql-action/upload-sarif@v3.36.2
        uses: github/codeql-action/upload-sarif@8272c299f21ca24af15dfe9ac0971ba969e5e0d5
        with:
          sarif_file: snyk.sarif